### ISSUE TITLE
Crash involving Xenon [Version 4.0.0]

### ISSUE THREAD

**Issue by catboycrimes** [AV306/xenon#10]
Installing CompleteConfig version 2.4.0 with version 4.0.0 Xenon provides the log below. I think you might have missed a tag? Note: It did not crash until I singled out Xenon, CompleteConfig, Fabric API, and Zoomify (+ its dependencies) as the only mods in the mods folder. The log isn't the one with Zoomify, as the crash was able to be reproduced without it. (Zoomify is incompatible with Xenon, fyi)

[16:08:43] [main/INFO]: Loading Minecraft 1.20.1 with Fabric Loader 0.14.21
[16:08:43] [main/WARN]: Warnings were found!
 - Mod 'Xenon' (xenon) 4.0.0+1.20.1 recommends version https://github.com/Lortseam/completeconfig of mod 'CompleteConfig' (completeconfig), but only the wrong version is present: 2.4.0!
	 - You should install version https://github.com/Lortseam/completeconfig of mod 'CompleteConfig' (completeconfig) for the optimal experience.
[16:08:43] [main/INFO]: Loading 58 mods:
	- completeconfig 2.4.0
	   |-- completeconfig-base 2.4.0
	   |-- completeconfig-gui-cloth 2.4.0
	   \-- completeconfig-gui-yacl 2.4.0
	- fabric-api 0.83.1+1.20.1
	|-- fabric-api-base 0.4.29+b04edc7a77
	   |-- fabric-api-lookup-api-v1 1.6.34+4d8536c977
	   |-- fabric-biome-api-v1 13.0.10+b3afc78b77
	   |-- fabric-block-api-v1 1.0.9+e022e5d177
	   |-- fabric-blockrenderlayer-v1 1.1.39+b3afc78b77
	   |-- fabric-client-tags-api-v1 1.0.20+b3afc78b77
	   |-- fabric-command-api-v1 1.2.32+f71b366f77
	   |-- fabric-command-api-v2 2.2.11+b3afc78b77
	   |-- fabric-commands-v0 0.2.49+df3654b377
	   |-- fabric-containers-v0 0.1.61+df3654b377
	   |-- fabric-content-registries-v0 4.0.7+b3afc78b77
	   |-- fabric-convention-tags-v1 1.5.3+b3afc78b77
	   |-- fabric-crash-report-info-v1 0.2.18+aeb40ebe77
	   |-- fabric-data-generation-api-v1 12.1.11+b3afc78b77
	   |-- fabric-dimensions-v1 2.1.51+b3afc78b77
	   |-- fabric-entity-events-v1 1.5.21+b3afc78b77
	   |-- fabric-events-interaction-v0 0.6.0+b3afc78b77
	   |-- fabric-events-lifecycle-v0 0.2.61+df3654b377
	   |-- fabric-game-rule-api-v1 1.0.38+b04edc7a77
	   |-- fabric-item-api-v1 2.1.26+b3afc78b77
	   |-- fabric-item-group-api-v1 4.0.7+b3afc78b77
	   |-- fabric-key-binding-api-v1 1.0.36+fb8d95da77
	   |-- fabric-keybindings-v0 0.2.34+df3654b377
	   |-- fabric-lifecycle-events-v1 2.2.20+b3afc78b77
	   |-- fabric-loot-api-v2 1.1.37+b3afc78b77
	   |-- fabric-loot-tables-v1 1.1.41+9e7660c677
	   |-- fabric-message-api-v1 5.1.6+b3afc78b77
	   |-- fabric-mining-level-api-v1 2.1.47+b3afc78b77
	   |-- fabric-models-v0 0.3.35+b3afc78b77
	   |-- fabric-networking-api-v1 1.3.8+b3afc78b77
	   |-- fabric-networking-v0 0.3.48+df3654b377
	   |-- fabric-object-builder-api-v1 11.0.6+b3afc78b77
	   |-- fabric-particles-v1 1.0.28+b3afc78b77
	   |-- fabric-recipe-api-v1 1.0.18+b3afc78b77
	   |-- fabric-registry-sync-v0 2.2.6+b3afc78b77
	   |-- fabric-renderer-api-v1 3.0.1+b3afc78b77
	   |-- fabric-renderer-indigo 1.3.1+b3afc78b77
	   |-- fabric-renderer-registries-v1 3.2.44+df3654b377
	   |-- fabric-rendering-data-attachment-v1 0.3.33+b3afc78b77
	   |-- fabric-rendering-fluids-v1 3.0.26+b3afc78b77
	   |-- fabric-rendering-v0 1.1.47+df3654b377
	   |-- fabric-rendering-v1 3.0.6+b3afc78b77
	   |-- fabric-resource-conditions-api-v1 2.3.5+ea08f9d877
	   |-- fabric-resource-loader-v0 0.11.7+f7923f6d77
	   |-- fabric-screen-api-v1 2.0.6+b3afc78b77
	   |-- fabric-screen-handler-api-v1 1.3.27+b3afc78b77
	   |-- fabric-sound-api-v1 1.0.12+b3afc78b77
	   |-- fabric-transfer-api-v1 3.2.2+b3afc78b77
	   \-- fabric-transitive-access-wideners-v1 4.2.0+b3afc78b77
	- fabricloader 0.14.21
	- java 17
	- minecraft 1.20.1
	- xenon 4.0.0+1.20.1
[16:08:43] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/me/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[16:08:43] [main/INFO]: Compatibility level set to JAVA_16
[16:08:43] [main/INFO]: Compatibility level set to JAVA_17
[16:08:43] [main/ERROR]: A mod crashed on startup!
net.fabricmc.loader.impl.FormattedException: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'xenon'!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:63) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:164) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.21.jar:?]
Caused by: java.lang.RuntimeException: Could not execute entrypoint stage 'preLaunch' due to errors, provided by 'xenon'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.21.jar:?]
	... 2 more
Caused by: java.lang.NoClassDefFoundError: me/shedaniel/math/Color
	at me.av306.xenon.config.feature.render.ProximityRadarGroup.<clinit>(ProximityRadarGroup.java:31) ~[xenon-4.0.0+1.20.1.jar:?]
	at me.av306.xenon.config.FeatureConfigGroup.<init>(FeatureConfigGroup.java:41) ~[xenon-4.0.0+1.20.1.jar:?]
	at me.av306.xenon.Xenon.<init>(Xenon.java:38) ~[xenon-4.0.0+1.20.1.jar:?]
	at me.av306.xenon.Xenon.<clinit>(Xenon.java:32) ~[xenon-4.0.0+1.20.1.jar:?]
	at me.av306.xenon.PreLaunchInitializer.onPreLaunch(PreLaunchInitializer.java:11) ~[xenon-4.0.0+1.20.1.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.21.jar:?]
	... 2 more
Caused by: java.lang.ClassNotFoundException: me.shedaniel.math.Color
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at me.av306.xenon.config.feature.render.ProximityRadarGroup.<clinit>(ProximityRadarGroup.java:31) ~[xenon-4.0.0+1.20.1.jar:?]
	at me.av306.xenon.config.FeatureConfigGroup.<init>(FeatureConfigGroup.java:41) ~[xenon-4.0.0+1.20.1.jar:?]
	at me.av306.xenon.Xenon.<init>(Xenon.java:38) ~[xenon-4.0.0+1.20.1.jar:?]
	at me.av306.xenon.Xenon.<clinit>(Xenon.java:32) ~[xenon-4.0.0+1.20.1.jar:?]
	at me.av306.xenon.PreLaunchInitializer.onPreLaunch(PreLaunchInitializer.java:11) ~[xenon-4.0.0+1.20.1.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:162) ~[fabric-loader-0.14.21.jar:?]
	... 2 more

**Comment by AV306** [comment]
Thanks for pointing this out! The 1.20 version isn’t fully ready yet, I’ll look into this issue :)

**Comment by AV306** [comment]
As a temporary fix, You can install Cloth Config, which should satisfy the `NoClassDefFoundError`
(Tested by @YeetBot3726)

EDIT: This seems to be the only way to stop this, since CompleteConfig's `gui-cloth` module just seems to be a wrapper and doesn't include everything in Cloth Config

**Comment by AV306** [comment]
Yeah, I entered the link to CompleteConfig instead of the version
